# Generated by Django 3.0.3 on 2020-03-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_htask_is_done'),
        ('app', '0004_event'),
    ]

    operations = [
    ]
