# Generated by Django 3.0.3 on 2020-03-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_htask'),
        ('app', '0007_merge_20200315_1319'),
    ]

    operations = [
    ]
